#!/bin/bash
php5=$(which php7.3 | grep -c "")
echo $php5
if [ $php5 -eq 0 ]
        then
                echo "php paigaldus"
		apt update
		sudo apt -y install lsb-release apt-transport-https ca-certificates
		sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
		echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php7.3.list
		apt update
		apt install php7.3-cli php7.3-fpm php7.3-json php7.3-pdo php7.3-mysql php7.3-zip php7.3-gd  php7.3-mbstring php7.3-curl php7.3-xml php7.3-bcmath php7.3-json libapache2-mod-php7.3 -y
else
                echo "php 7.3 on juba paigaldatud"
fi
