#!/bin/bash
#LEMP-stack install script

apt update && apt -upgrade -y
sudo apt -y install lsb-release apt-transport-https ca-certificates
                sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
                echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php7.3.list
		apt install nginx -y
		apt install mysql-server -y
		apt install phpmyadmin
                apt install php7.3-cli php7.3-fpm php7.3-json php7.3-pdo php7.3-mysql php7.3-zip php7.3-gd  php7.3-mbstring php7.3-curl php7.3-xml php7.3-bcmath php7.3-json libapache2-mod-php7.3 -y
		cd /var/www/html/ #vahetab kausta
	wget https://wordpress.org/latest.tar.gz #laeb alla kõige uuema wordpressi
	tar xpf latest.tar.gz #pakib lahti tar faili
	chown -R www-data:www-data /var/www/html #vahetab html kausta õigused
	rm latest.tar.gz
	rm index.html
	touch /etc/nginx/sites-available/wordpress.conf
	echo "server {
		listen 80 default_server;
		listen [::]:80 default_server;

        	root /var/www/html/wordpress;

        	index index.php;

        	server_name _;

        	location / {
                	try_files $uri $uri/ =404;
		        }
		}
	"
	ln -s /etc/nginx/sites-available/wordpress.conf /etc/nginx/sites-enabled/

